apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres/secret.yml
  - postgres/pvc.yml
  - postgres/statefulset.yml
  - postgres/service.yml
  - backend/configmap.yml
  - backend/deployment.yml
  - backend/service.yml
  - backend/hpa.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - ingress.yml
