apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - namespace.yml
images:
  - name: ghcr.io/toyonix/gitops-terraform-kubernates/backend
    newTag: dev
  - name: ghcr.io/toyonix/gitops-terraform-kubernates/frontend
    newTag: dev
patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.devops-depi.duckdns.org
    target:
      kind: Ingress
      name: inventory-ingress
  - patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 1
    target:
      kind: HorizontalPodAutoscaler
